In [15]:
##########    Importing Libraries   ##########

import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, cross_val_score
import pandas_profiling as pdp
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import svm
from sklearn import ensemble
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
%matplotlib inline
plt.style.use('fivethirtyeight')


In [16]:
######## Dataset loading: Train & Test  ######### 

train = pd.read_csv('train.csv.zip')
test = pd.read_csv('test.csv.zip')
test_1 = pd.read_csv('test.csv.zip')


# train.head()

In [17]:
######## Fill na values with median ######### 

train = train.fillna(train.median())
test = test.fillna(test.median())

# train.head()

In [18]:
######## Assigned response in the train into the y_train ########
y_train = train["Response"]

######## Drop Response ID and Product info 2 from train data ########
train = train.drop(['Response','Id','Product_Info_2'], axis = 1)

######## Drop ID and Product info 2 from test data ########
test = test.drop(['Id','Product_Info_2'], axis = 1)

In [19]:
######## Convert train and test data into float ########
train = train.astype(float)
test = test.astype(float)
# train.head()

In [20]:
######## Splitting the train data into two sets of 80-20 for training and testing respectively ######## 

x_train = train
X_train, X_test, y_train, y_test = train_test_split(x_train, y_train, test_size=0.2)


In [21]:
######## Applying random forest Classifier ########
######## Taking in Account the following ########
######## Trying with different n_estimator ########
######## Using criterion as gini ########
######## Let the tree  expand until every leaf is pure ie leaving the max_depth default ########

RF = RandomForestClassifier(n_estimators = 200, criterion = 'gini')
RF.fit(X_train, y_train)
y_pred_rf = RF.predict(X_test)


# print(y_pred_rf)

In [22]:
accuracy_score(y_test, y_pred_rf)

0.5682411383345963

In [23]:
print(confusion_matrix(y_test, y_pred_rf))

[[ 236  175   21   38   94  303  108  299]
 [ 111  314   26   32  152  326  127  277]
 [  18   13   81   54   10   12    0    4]
 [   8    1   13  216    0   24    4   29]
 [  28   93    0    0  566  231   55  112]
 [  71   68    1    4   95 1250  221  513]
 [  25    7    0    1   12  392  589  591]
 [  12    4    0    3    3  196  111 3497]]


In [24]:
print(classification_report(y_test, y_pred_rf))

              precision    recall  f1-score   support

           1       0.46      0.19      0.26      1274
           2       0.47      0.23      0.31      1365
           3       0.57      0.42      0.49       192
           4       0.62      0.73      0.67       295
           5       0.61      0.52      0.56      1085
           6       0.46      0.56      0.50      2223
           7       0.48      0.36      0.42      1617
           8       0.66      0.91      0.76      3826

    accuracy                           0.57     11877
   macro avg       0.54      0.49      0.50     11877
weighted avg       0.55      0.57      0.54     11877

